language: ruby
rvm:
  - 2.2.6
  - 2.3.2

gemfile:
  - gemfiles/active_job_42.gemfile
  - gemfiles/active_job_50.gemfile
  - gemfiles/active_job_51.gemfile
  - gemfiles/active_job_master.gemfile

before_install: gem install bundler

matrix:
  allow_failures:
  - gemfile: gemfiles/active_job_master.gemfile

services:
  - redis
